name: Bundle install

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add Homebrew to $PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: brew bundle install --file=Brewfile
